---
title: "presentation"
format: revealjs
editor: visual
---

## Report no. of alternatives, attributes, levels, block

-   2 alternatives for each choice set

-   4 attributes (spatial scale, BCG change scenario, Location, annual tax increase)

-   Levels per attribute: (3, 4, 2, 10)

-   Five blocks

## Total number of possible choice set

(3*4*2\*10)\^2 = 57 600

## Blocks

They had 10 blocks (in two different groups). In one group of blocks they kept spatial unit (combination of spatial scale and location) constant, in the other group they kept the change in environmental status constant. Each respondent got assigned to 2 blocks, either in spatial or the environmental category.

### Spatial unit constant (5 blocks):

-   Single watershed + Policy area includes home watershed (local)
-   Single watershed + Policy area does not includes home watershed (non-local)
-   Three contiguous watersheds + Policy area includes home watershed (local)
-   Three contiguous watersheds + Policy area does not includes home watershed (non-local)
-   Full study region (including home)
